using System;
using System.Threading.Tasks;
using WebAssemblySharp.Attributes;
using WebAssemblySharp.Runtime;
using WebAssemblySharpExampleData;

namespace WebAssemblySharpTest.Runtime;

[TestClass]
public class InterfaceTest
{
    
    [TestMethod]
    [DynamicData(nameof(TestRuntimeProvider.RuntimeTypes), typeof(TestRuntimeProvider))]
    public async Task ExecuteAddWasmTest(Type p_RuntimeType)
    {
        IAdd l_Module = await WebAssemblyRuntimeBuilder.CreateSingleModuleRuntime<IAdd>(p_RuntimeType);
        int l_Result = await l_Module.add( 1, 2);
        Assert.AreEqual(3, l_Result);
    }
    
    
    [TestMethod]
    [DynamicData(nameof(TestRuntimeProvider.RuntimeTypes), typeof(TestRuntimeProvider))]
    public async Task ExecuteAddAutoGenWasmTest(Type p_RuntimeType)
    {
        IAddAutoGen l_Module = await WebAssemblyRuntimeBuilder.CreateSingleModuleRuntime<IAddAutoGen>(p_RuntimeType);
        int l_Result = await l_Module.add( 1, 2);
        Assert.AreEqual(3, l_Result);
    }
    
    
    [TestMethod]
    [DynamicData(nameof(TestRuntimeProvider.RuntimeTypes), typeof(TestRuntimeProvider))]
    public async Task ExecuteAddAutoGenWasmSameProjectTest(Type p_RuntimeType)
    {
        IAddAutoGenSameProject l_Module = await WebAssemblyRuntimeBuilder.CreateSingleModuleRuntime<IAddAutoGenSameProject>(p_RuntimeType);
        int l_Result = await l_Module.add( 1, 2);
        Assert.AreEqual(3, l_Result);
    }
    
    [TestMethod]
    [DynamicData(nameof(TestRuntimeProvider.RuntimeTypes), typeof(TestRuntimeProvider))]
    public async Task ExecuteLocalAutoGenWasmTest(Type p_RuntimeType)
    {
        ILocalAutoGen l_Module = await WebAssemblyRuntimeBuilder.CreateSingleModuleRuntime<ILocalAutoGen>(p_RuntimeType);
        (int, int, int) l_Tuple = await l_Module.unnamed_locals( 11, 22);
        
        Assert.AreEqual(11, l_Tuple.Item1);
        Assert.AreEqual(22, l_Tuple.Item2);
        Assert.AreEqual(44, l_Tuple.Item3);
    }
    
}


[WebAssemblyModuleManifestResource("WebAssemblySharpExampleData.Programms.add.wasm", typeof(WebAssemblyExamples))]
[WebAssemblyModuleDefinition("add")]
public interface IAdd
{
    public ValueTask<int> add(int p_A, int p_B);
}


[WebAssemblyModuleManifestResource("WebAssemblySharpExampleData.Programms.add.wasm", typeof(WebAssemblyExamples))]
[WebAssemblyModuleDefinition("add")]
public partial interface IAddAutoGen
{
    // The methods in this interface are auto-generated by the WebAssemblySharp tool.
}


[WebAssemblyModuleManifestResource("WebAssemblySharpTest.Programms.add.wasm")]
[WebAssemblyModuleDefinition("add")]
public partial interface IAddAutoGenSameProject
{
    // The methods in this interface are auto-generated by the WebAssemblySharp tool.
}

[WebAssemblyModuleManifestResource("WebAssemblySharpExampleData.Programms.locals.wasm", typeof(WebAssemblyExamples))]
[WebAssemblyModuleDefinition("add")]
public partial interface ILocalAutoGen
{
    // The methods in this interface are auto-generated by the WebAssemblySharp tool.
}

