# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags:
    - "*"
  pull_request:
    branches: [ "main" ]
  
env:
  VERSION: "99.0.0-Test"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Version Variable
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=$VERSION
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: upload nuget package
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: |
        dotnet pack WebAssemblySharp/WebAssemblySharp.csproj --output nupkgs /p:PackageVersion=$VERSION
        dotnet pack WebAssemblySharp.InterfaceGenerator/WebAssemblySharp.InterfaceGenerator.csproj --output nupkgs /p:PackageVersion=$VERSION
        dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        
